# -*- coding: utf-8 -*-
"""Szakdolgozat_kmer_generálás.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18JAMdyNJWayTCxHJJnVLuM3napksZnqC

# Szakdolgozat - Adathalmaz készítés: k-merek készítése FNA fájlokból
"""

import os
from google.colab import drive

drive.mount('/content/drive/')

os.chdir('/content/drive/MyDrive/Iskolai/Egyetem/Szakdolgozat')

# az adott szekvecniából kmereket visszaadó függvény, k a kmer hossza, a shift a lépéshossz a kmerek között
def create_kmers(seq, k, shift):
  for x in range(0, len(seq)-k, shift):
    yield seq[x:x+k]

# függvény, amely az adott paraméterek alapján kmereket tartalmazó fájlt csinál a bemeneti FNA fájlból

# a fullfile paraméterre a tesztelés folyamán volt szükség, ez limitálta a kimeneti fájlban keletkező k-merek számát, így viszonylag egyszerűen vissza lehetett követni,
# hogy a k-mergenerálás megfelelően működik-e
def make_kmers(ifname, ofname, length = 15, shift = 5, fullfile=True):
  kmers = [] # a fájlból származó összes kmer
  with open(ifname, "r") as ins:
    lines = ins.read().splitlines() # sorok olvasása, sorvégi \n eltávolítása

    genome_lines = [] # adott genomot tartalmazó lista
    i = 0

    for line in lines:
      if line.startswith(">"):
        if (len(genome_lines) == 0):
          continue
        else:
          gen_seq = ''.join(genome_lines) # adott genomot tartalmazó listából készített folytonos string
          gen_kmers = create_kmers(gen_seq, length, shift) # adott genomból létrehozott kmerek
          for x in gen_kmers:
            kmers.append(x)
          genome_lines = []
          i = i+1
          if not fullfile and i==1:
            break
      else:
        genome_lines.append(line)

      if not (len(genome_lines) == 0):
        gen_seq = ''.join(genome_lines) # adott genomot tartalmazó listából készített folytonos string
        gen_kmers = create_kmers(gen_seq, length, shift)
        for x in gen_kmers:
          kmers.append(x)
        genome_lines = []

  with open(ofname, "w") as out:
    kmers_for_file = [x + '\n' for x in kmers]
    out.writelines(kmers_for_file)

# példa futtatás, hogy a generálás megfelelően működik-e
make_kmers('viral_fasta_for_test.txt', 'viral_kmers_test.txt', fullfile=False)

